export enum SLICE_NAME {
  APP = 'APP',

  AUTH = 'AUTH',

  PROFILE = 'PROFILE',

  SUPPORTED_LOCATION = 'SUPPORTED_LOCATION',

  USERS = 'USERS',

  USER = 'USER',
  USER_ADDRESS = 'USER_ADDRESS',

  ORDER = 'ORDER',
  ESTIMATED_COST = 'ESTIMATED_COST',

  NOTIFICATION = 'NOTIFICATION',

  DASHBOARD = 'DASHBOARD',
}
